name: Deploy development

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        env:
          REDIS_PORT: 6390
        ports:
          - 6390:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        uses: ./.github/actions/run-tests

  build-push-ecr:
    name: Push
    uses: ./.github/workflows/build-push-ecr.yml
    needs: test
    with:
      environment: development
      service-name: webhook
    secrets: inherit

  deploy-ecs:
    name: Deploy
    uses: ./.github/workflows/deploy-ecs.yml
    needs: build-push-ecr
    with:
      environment: development
      ecr-image: ${{ needs.build-push-ecr.outputs.ecr-image }}
      cluster-name: core-services
      service-name: webhook
      cluster-suffix: g8M6HWc0Cdph
      service-suffix: 5MUPY9GspHiI
    secrets: inherit
